[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
logistics_traceability = "CqNEvq5AtuZH7ffQCrt63m5M9g3MLhsvgVnXYS5fMbEc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -- --test-threads=1"
